services:
  postgres:
    image: postgres:15
    container_name: elocidadao-postgres
    environment:
      POSTGRES_USER: elocidadao
      POSTGRES_PASSWORD: elocidadao123
      POSTGRES_DB: elocidadao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data